#!/usr/bin/env ruby

require 'thor'
require 'shellwords'
require 'net/ssh'

class Cluster
  attr_accessor :user, :ssh_key, :server_ip
  attr_accessor :location
  def initialize(p_server_ip, options = {})
    @server_ip = p_server_ip
    if options[:user] && !options[:user].empty?
      self.user = options[:user]
    else
      self.user = 'ubuntu'
    end

    if options[:ssh_key] && !options[:ssh_key].empty?
      self.ssh_key = options[:ssh_key]
    else
      self.ssh_key = File.expand_path(File.join(ENV['HOME'], ".ssh/google_compute_engine"))
    end

    if options[:location] && !options[:location].empty?
      self.location = options[:location]
    end
  end

  def create
    create_dir_cmd = ["ssh", "-i", ssh_key, "#{user}@#{server_ip}", "mkdir -p ~/gce_invoker"]
    dir_create_string = Shellwords.join(create_dir_cmd)
    run_and_exit(dir_create_string)

    rsyc_array = ["rsync", "-Pav", '-e', ssh_option, ".", "#{user}@#{server_ip}:gce_invoker/"]
    rsync_cmd = Shellwords.join(rsyc_array)
    run_and_exit(rsync_cmd)

    ans_arr1 = ["ssh", "-i", ssh_key, "#{user}@#{server_ip}", "cd ~/gce_invoker/ansible-playbook && sudo ./bootstrap.sh"]
    ans_cmd1 = Shellwords.join(ans_arr1)
    run_and_exit(ans_cmd1)

    if local_upload?
      sync_local_kube(location)
    else
      ans_arr2 = ["ssh", "-i", ssh_key, "#{user}@#{server_ip}", "cd ~/gce_invoker/ansible-playbook && ansible-playbook kube.yaml"]
      ans_cmd2 = Shellwords.join(ans_arr2)
      run_and_exit(ans_cmd2)
    end

    invoker_arr = ["ssh", "-i", ssh_key, "#{user}@#{server_ip}", "cd ~/gce_invoker/ansible-playbook && ansible-playbook invoker.yaml"]
    invoker_cmd = Shellwords.join(invoker_arr)
    run_and_exit(invoker_cmd)
  end

  def run_and_exit(cmd)
    system(cmd)
    if $? != 0
      puts "Error running #{cmd}"
      exit(1)
    end
  end

  def ssh_option
    "ssh -i #{ssh_key}"
  end

  def local_upload?
    location && !location.empty?
  end

  # copy local files to path
  def sync_local_kube(kube_binary_path)
    rsyc_array = [
      "rsync", "-Pavz", '-e', ssh_option,
      "--exclude-from", "exclude_list.txt",
      kube_binary_path, "#{user}@#{server_ip}:kube_binary/"
    ]
    rsync_cmd = Shellwords.join(rsyc_array)
    system(rsync_cmd)

    ans_arr2 = ["ssh", "-i", ssh_key, "#{user}@#{server_ip}", "cd ~/gce_invoker/ansible-playbook && ansible-playbook copy_k8s.yaml"]
    ans_cmd2 = Shellwords.join(ans_arr2)
    system(ans_cmd2)
  end
end

class ClusterCLI < Thor
  def self.start(*args)
    cli_args = args.flatten
    # If it is not a valid task, it is probably file argument
    if default_create_command?(cli_args)
      args = [cli_args.unshift("create")]
    end
    super(*args)
  end

  desc "create", "Create a kubernetes cluster"
  method_option :ssh_key,
    type: :string,
    desc: "SSH key to use for login",
    aliases: [:k]
  method_option :user,
    type: :string,
    desc: "User to use, default: Ubuntu",
    aliases: [:u]
  method_option :location,
    type: :string,
    desc: "Location of local kube binaries",
    aliases: [:l]
  def create(server_ip)
    cluster = Cluster.new(server_ip, options)
    cluster.create
  end

  private
  def self.default_create_command?(args)
    command_name = args.first
    command_name &&
      !command_name.match(/^-/) &&
      !valid_tasks.include?(command_name)
  end

  def self.valid_tasks
    tasks.keys + ["help"]
  end
end

ClusterCLI.start(ARGV)
