---
- hosts: all

- hosts: all
  vars:
    nonroot_user: '{{ ansible_env.SUDO_USER }}'
  tasks:
    - name: Install basic packages
      apt: name={{item}} state=installed
      with_items:
        - build-essential
        - ruby
        - ruby-dev
        - ruby-bundler
        - git
        - libxml2-dev
        - wget
        - docker.io
        - htop
    - name: Install go
      command: "{{item}} chdir=/usr/local creates=/usr/local/go"
      with_items:
        - "wget -nv https://storage.googleapis.com/golang/go1.7.linux-amd64.tar.gz"
        - "tar -zxf go1.7.linux-amd64.tar.gz"
    - name: Add GOROOT
      lineinfile:
        dest: /etc/environment
        line: "export GOROOT='/usr/local/go'"
    - name: add GOROOT to path
      lineinfile: >
        dest=/etc/environment
        state=present
        backrefs=yes
        regexp='PATH=(["]*)((?!.*?/usr/local/go/bin).*?)(["]*)$'
        line="PATH=\1\2:/usr/local/go/bin\3"
    - name: Clone invoker
      command: >
        chdir=/tmp
        creates=/tmp/invoker_gem
        git clone https://github.com/code-mancers/invoker.git invoker_gem
    - name: Check if cloned
      stat:
        path: /tmp/invoker_gem
      register: invoker_stat_result
    - name: Install invoker
      command: "{{item}} chdir=/tmp/invoker_gem creates=/usr/local/bin/invoker"
      with_items:
        - "gem build invoker.gemspec"
        - "gem install invoker-1.5.2.gem"
      when: invoker_stat_result.stat.exists == True
    - name: Reset permissions of ansible
      command: "chown -R {{nonroot_user}}:{{nonroot_user}} /home/{{nonroot_user}}/.ansible"
    - name: Configure Cloud
      command: "mkdir -p /etc/cloud"
    - name: Create cloud config file
      template: >
        src=invoker_files/{{ansible_local.cloud.general.name}}.j2
        dest=/etc/cloud/{{ansible_local.cloud.general.name}}.conf
    - name: Copy flanneld system unit files
      template: >
        src=invoker_files/flanneld.j2
        dest=/etc/systemd/system/flanneld.service
    - name: stop flanneld if running
      systemd: "name=flanneld daemon_reload=yes enabled=yes state=stopped"
      ignore_errors: yes
    - name: Create flanneld install directory
      command: "mkdir -p /tmp/flanneld"
    - name: copy the fl config
      copy: >
        src=invoker_files/fl_config.json
        dest=/tmp/flanneld/fl_config.json
    - name: copy docker config file
      copy: >
        src=invoker_files/docker.conf
        dest=/tmp/flanneld/docker.conf
    - name: Download and install flanneld
      command: "{{item}} chdir=/tmp/flanneld creates=/usr/bin/flanneld"
      with_items:
        - "wget -nv https://github.com/coreos/flannel/releases/download/v0.6.2/flannel-v0.6.2-linux-amd64.tar.gz"
        - "tar -zxf flannel-v0.6.2-linux-amd64.tar.gz"
        - "cp flanneld /usr/bin/."
