---
- hosts: all

- hosts: all
  vars:
    k8s_home: "/home/{{ansible_env.USER}}/kube_binary"
    nonroot_user: '{{ ansible_env.USER }}'
  environment:
    GOPATH: "/home/{{nonroot_user}}/goal"
    GOROOT: /usr/local/go
    PATH: '{{ ansible_env.PATH }}:/home/{{nonroot_user}}/goal/bin:/usr/local/go/bin'
  tasks:
    - name: Check if invoker is running
      stat:
        path: /tmp/invoker
      register: invoker_state
    - name: Stop invoker if running
      command: >
        invoker stop
      become: true
      when: invoker_state.stat.exists == True
    - name: Copy the binaries
      command: >
        chdir={{ k8s_home }}/
        cp {{item}} /usr/local/bin/
      with_items:
        - kubectl
        - kube-apiserver
        - kube-dns
        - kube-controller-manager
        - kubelet
        - kube-scheduler
        - kube-proxy
      become: true
