---
- hosts: all

- hosts: all
  vars:
    k8s_home: "/home/{{ansible_env.USER}}/kube_binary"
    nonroot_user: '{{ ansible_env.USER }}'
  environment:
    GOPATH: "/home/{{nonroot_user}}/goal"
    GOROOT: /usr/local/go
    PATH: '{{ ansible_env.PATH }}:/home/{{nonroot_user}}/goal/bin:/usr/local/go/bin'
  tasks:
    - name: Check if invoker is running
      stat:
        path: /tmp/invoker
      register: invoker_state
    - name: Stop invoker if running
      command: >
        invoker stop
      become: true
      when: invoker_state.stat.exists == True
    - name: Copy kubectl
      copy: >
        src={{k8s_home}}/kubectl
        dest=/usr/local/bin/kubectl
    - name: Copy kube-apiserver
      copy: >
        src={{k8s_home}}/kube-apiserver
        dest=/usr/local/bin/kube-apiserver
    - name: Copy kube-dns
      copy: >
        src={{k8s_home}}/kube-dns
        dest=/usr/local/bin/kube-dns
    - name: Copy kube-controller-manager
      copy: >
        src={{k8s_home}}/kube-controller-manager
        dest=/usr/local/bin/kube-controller-manager
    - name: Copy kubelet
      copy: >
        src={{k8s_home}}/kubelet
        dest=/usr/local/bin/kubelet
    - name: Copy kube-scheduler
      copy: >
        src={{k8s_home}}/kube-scheduler
        dest=/usr/local/bin/kube-scheduler
    - name: Copy kube-proxy
      copy: >
        src={{k8s_home}}/kube-proxy
        dest=/usr/local/bin/kube-proxy
