---
- hosts: all

- hosts: all
  vars:
    nonroot_user: '{{ ansible_env.SUDO_USER }}'
  tasks:
    - name: Copy flanneld system unit files
      template: >
        src=invoker_files/flanneld.j2
        dest=/etc/systemd/systemd/flanneld.service
    - name: stop flanneld if running
      systemd: "name=flanneld daemon_reload=yes enabled=yes state=stopped"
      ignore_errors: yes
    - name: Create flanneld install directory
      command: "mkdir -p /tmp/flanneld"
    - name: copy the fl config
      copy: >
        src=invoker_files/fl_config.json
        dest=/tmp/flanneld/fl_config.json
    - name: Download and install flanneld
      command: "{{item}} chdir=/tmp/flanneld creates=/usr/bin/flanneld"
      with_items:
        - "wget -nv https://github.com/coreos/flannel/releases/download/v0.6.2/flannel-v0.6.2-linux-amd64.tar.gz"
        - "tar -zxf flannel-v0.6.2-linux-amd64.tar.gz"
        - "cp flanneld /usr/bin/."
    - name: Check etcd key
      command: "Run emacs"
    - name: Add flannel config to etcd
      command: "etcdctl set /coreos.com/network/config < invoker_files/fl_config.json"
