---
- hosts: all

- hosts: all
  vars:
    k8s_home: "/home/{{ansible_env.USER}}/goal/src/k8s.io/kubernetes"
    nonroot_user: '{{ ansible_env.USER }}'
    invoker_root: '/home/{{nonroot_user}}/invoker_files'
  environment:
    GOPATH: "/home/{{nonroot_user}}/goal"
    GOROOT: /usr/local/go
    PATH: '{{ ansible_env.PATH }}:/home/{{nonroot_user}}/goal/bin:/usr/local/go/bin'
  tasks:
    - name: Create invoker directory
      command: mkdir -p ~/invoker_files
    - name: Copy invoker.ini files
      template: >
        src=invoker_files/invoker.j2
        dest=~/invoker_files/invoker.ini
    - name: Check if Invoker is running
      stat:
        path: /root/.invoker/invoker.pid
      register: invoker_state
      become: true
    - name: Start invoker
      command: >
        chdir={{invoker_root}}
        invoker start invoker.ini -d
      become: true
      when: invoker_state.stat.exists == False
    - name: Configure kubectl
      command: >
        chdir={{invoker_root}}
        {{item}}
      with_items:
        - "kubectl config set-cluster local --server=0.0.0.0:8080 --kubeconfig={{nonroot_user}}/.kube/config"
        - "kubectl config set-context local --cluster=local"
        - "kubectl config use-context local"
