---
- hosts: all

- hosts: all
  vars:
    nonroot_user: '{{ ansible_env.SUDO_USER }}'
  tasks:
    - name: Install etcd service
      template: >
        src=invoker_files/etcd.j2
        dest=/etc/systemd/system/etcd.service
    - name: stop etcd systemd
      systemd: "name=etcd daemon_reload=yes enabled=yes state=stopped"
      ignore_errors: yes
    - name: Install etcd
      command: "{{item}} chdir=/tmp creates=/usr/bin/etcdctl"
      with_items:
        - "wget -nv https://github.com/coreos/etcd/releases/download/v3.0.15/etcd-v3.0.15-linux-amd64.tar.gz"
        - "tar -zxf etcd-v3.0.15-linux-amd64.tar.gz"
        - "cp etcd-v3.0.15-linux-amd64/etcd /usr/bin/."
        - "cp etcd-v3.0.15-linux-amd64/etcdctl /usr/bin/."
    - name: start etcd systemd
      systemd: "name=etcd daemon_reload=yes enabled=yes state=started"
    - name: wait for 10 seconds before next step
      pause:
        prompt: "wait for 10 seconds for etcd config"
        seconds: 10
    - name: Check etcd key
      command: "etcdctl get /coreos.com/network/config"
      ignore_errors: yes
      register: etcd_config_check
    - name: Add flannel config to etcd
      when: etcd_config_check|failed
      shell: etcdctl set /coreos.com/network/config < /tmp/flanneld/fl_config.json
      retries: 5
      delay: 1
      register: task_result
      until: task_result.rc == 0
    - name: start flanneld
      systemd: "name=flanneld enabled=yes state=started"
    - name: wait for 10 seconds
      pause:
        prompt: "wait for 10 seconds for flanneld config"
        seconds: 10
    - name: stop flanneld
      systemd: "name=flanneld enabled=yes state=stopped"
      ignore_errors: yes
    - name: stop docker
      systemd: "name=docker enabled=yes state=stopped"
    - name: configure docker
      command: "{{item}} chdir=/tmp/flanneld"
      with_items:
        - "./mk-docker-opts.sh"
        - "mkdir -p /etc/systemd/system/docker.service.d/"
        - "cp docker.conf /etc/systemd/system/docker.service.d/"
    - name: start flanneld
      systemd: "name=flanneld enabled=yes state=started"
    - name: start docker
      systemd: "name=docker enabled=yes state=started"
